services:
  web:
    build:
      context: . # Builds the image using the Dockerfile in the current directory
    container_name: streamlit-dev
    command: streamlit run app.py --server.port 8501 --server.enableCORS false
    ports:
      - "8501:8501" # Expose port 8501 for Streamlit
    volumes:
      - /host_mnt/c/Dev/python-env/media/movie:/media/movie
      - /host_mnt/c/Dev/python-env/media/tv_show:/media/tv_show
      - .:/app # Mount the current directory into /app in the container
    working_dir: /app # Set the working directory inside the container
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - postgres
    networks:
      - pgnetwork

  postgres:
    build:
      context: ./postgres
      dockerfile: postgres.Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init-scripts:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=postgres
    networks:
      - pgnetwork

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - pgnetwork

networks:
  pgnetwork:
    driver: bridge

volumes:
  postgres_data:
